### ISSUE TITLE
月圆 | 桥边红药的博客

### ISSUE THREAD

**Issue by promefire** [promefire/myBlogComment#2]
https://promefire.github.io/post/%E6%9C%88%E5%9C%86.html 

 乌鸦，古钟与残破的手稿，静静地诉说着一场月圆之夜的伟大实验。   阴影飞起，扬起一团旧日的烟尘，绯红的月光透过茂林的缺口，黑暗中堆积的枯叶染上了诡异的红晕。 凄风，苦雨，寒灯，夜行人。   马车伴着古老嘶哑的钟声抵达破败小屋，下马，站定，黑黄干燥的手掌拂去木门上历史的迷雾，不规则的暗红显现，仿若被血浸染千百年。   屋内灯火闪烁，但昏暗无比，老者扶着墙壁，点燃手中的油灯，寻找着前行的路。   火焰

**Comment by promefire** [comment]
123

**Comment by GZ-Metal-Cell** [comment]
什么乱七八糟的
