### ISSUE TITLE
微信公众号推送天气预报 | 桥边红药的博客

### ISSUE THREAD

**Issue by promefire** [promefire/myBlogComment#28]
https://promefire.github.io/post/%E5%BE%AE%E4%BF%A1%E5%85%AC%E4%BC%97%E5%8F%B7%E6%8E%A8%E9%80%81%E5%A4%A9%E6%B0%94%E9%A2%84%E6%8A%A5.html 

 推送天气预报，没成功，因为是个人公众号

**Comment by GZ-Metal-Cell** [comment]
这个公众号是啥来着

**Comment by promefire** [comment]
> @GZ-Metal-Cell
> 这个公众号是啥来着
 不存在邮局
