### ISSUE TITLE
hexo恢复及使用hexon实现在线编辑同步 | 桥边红药的博客

### ISSUE THREAD

**Issue by promefire** [promefire/myBlogComment#29]
https://promefire.github.io/post/hexo%E5%9C%A8%E7%BA%BF%E7%BC%96%E8%BE%91%E5%90%8C%E6%AD%A5.html?#%E9%83%A8%E7%BD%B2hexon 

 前言hexo是一个轻量级的博客主题框架，挂载GitHub上不用太操心，但是有一点不方便的是hexo没有后台，每次发博都要本地写好然后hexo三件套，最近发现了一个hexon的GUI，可以实现hexo的在线编辑部署。ps-需要一台服务器 博客恢复1、安装npm、hexo、pnpm、git npm  在这里 下载npm，可以离线下载，也可以使用wget下载解压tar -zxvf node-v10.24

**Comment by GZ-Metal-Cell** [comment]
好不好使啊

**Comment by promefire** [comment]
> @GZ-Metal-Cell
> 好不好使啊

除了写文章用markdown的时候是源代码格式，预览得返回上一个界面，部署和备份都挺方便

**Comment by GZ-Metal-Cell** [comment]
> @promefire
> > @GZ-Metal-Cell
> > 好不好使啊
> 
> 除了写文章用markdown的时候是源代码格式，预览得返回上一个界面，部署和备份都挺方便

真是太厉害了！
